### ISSUE TITLE
Horizontal scrollbar on homepage

### ISSUE THREAD

**Issue by jbelien** [HackYourFutureBelgium/hackyourfuture.be#1]
For some reason, I have a horizontal scrollbar only on the homepage (Windows 10 Firefox 80).

Horizontal scrollbar is caused by the gray "background block" behind the picture in "Our program" section.
See [`image-description/style.js#L58-L67`](https://github.com/HackYourFutureBelgium/HackYourFutureBelgium.github.io/blob/dev/src/components/page-sections/image-description/style.js#L58-L67)

**EDIT:** It only happens on screen `<= 1750px`

**Comment by colevandersWands** [comment]
@KevinTss, let's take a look at this after the deployment is set up?

**Comment by KevinTss** [comment]
Yeah I assign myself, will fix that
