### ISSUE TITLE
Fix ESLint configuration

### ISSUE THREAD

**Issue by jbelien** [HackYourFutureBelgium/hackyourfuture.be#11]
```
Error: .eslintrc.js:
	Configuration for rule "required" is invalid:
	Severity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed '{ some: [ "nesting", "id" ] }').
```

See https://github.com/HackYourFutureBelgium/hackyourfuture.be/runs/1194643281?check_suite_focus=true#step:6:11

**Comment by lpmi-13** [comment]
which rule were you trying to add here? I'm not seeing anything for "required", "nesting", or "id" in the list of available rules here:
https://eslint.org/docs/2.0.0/rules/

**Comment by lpmi-13** [comment]
a working eslint config for warning on inner block declarations, for example, would look something like:
```
module.exports = {
  globals: {
    __PATH_PREFIX__: true,
  },
  extends: `react-app`,
  rules: {
    "no-inner-declarations": 1
  },
}
```

**Comment by jbelien** [comment]
> which rule were you trying to add here? I'm not seeing anything for "required", "nesting", or "id" in the list of available rules here:
> https://eslint.org/docs/2.0.0/rules/

Indeed, I have no idea. `.eslintrc.js` was added by @KevinTss in abd8d283db8b84fafc61c61979bd6868737b4ce4

**Comment by lpmi-13** [comment]
Ah, got it. Just to get CI working we could either remove that bit or add something similar to what I suggested above.
