### ISSUE TITLE
address warnings from CI

### ISSUE THREAD

**Issue by lpmi-13** [HackYourFutureBelgium/hackyourfuture.be#14]
I noticed there seem to be a lot of declared by unused items flagged in

https://github.com/HackYourFutureBelgium/hackyourfuture.be/actions/runs/285641219

So I'm happy to address those in a PR if that would be helpful.

**Comment by jbelien** [comment]
All help is more than welcome @lpmi-13 !
Thanks a lot :)

**Comment by lpmi-13** [comment]
PR opened here https://github.com/HackYourFutureBelgium/hackyourfuture.be/pull/15

**Comment by lpmi-13** [comment]
PR merged, so this can be closed now.
