### ISSUE TITLE
include simple E2E tests to make sure all the pages render and are navigable

### ISSUE THREAD

**Issue by lpmi-13** [HackYourFutureBelgium/hackyourfuture.be#16]
Currently, the CI "test" step is only invoking the linter, so it would be nice to ensure in CI that none of the pages are broken by any commits.

Cypress is super straightforward to set up for this for local development, and already has some nice github actions set up (https://www.cypress.io/blog/2019/11/20/drastically-simplify-your-testing-with-cypress-github-action/), so this would be my recommendation, but probably needs a bit of discussion.

Are there any other "lets make sure the pages can be clicked through" suggestions for a framework to add? We should also probably add some unit testing, but that would (ideally) be component-specific rather than ensuring that the website is usable.

**Comment by jbelien** [comment]
Definitely a good idea!
I have no experience with Cypress so I'll follow your lead and suggestions on this one 👌

**Comment by lpmi-13** [comment]
opened a PR here:

https://github.com/HackYourFutureBelgium/hackyourfuture.be/pull/20

**Comment by lpmi-13** [comment]
PR has been merged, so closing for now and we can revisit when we decide which more extensive UI testing we want.
