### ISSUE TITLE
Choose license

### ISSUE THREAD

**Issue by jbelien** [HackYourFutureBelgium/hackyourfuture.be#19]
I noticed that we are still using the Gatsby default [`LICENSE` file](https://github.com/HackYourFutureBelgium/hackyourfuture.be/blob/main/LICENSE) ("0BSD License").
That's not a license we usually use at @openknowledgebe ; should we change to our usual "MIT License" ?
You can find more information here : <https://choosealicense.com/>

---

Since @lpmi-13 contributed to the project, we need his/her consent to change the license.

**Comment by lpmi-13** [comment]
I'm 100% fine with updating it
