### ISSUE TITLE
Repository structure

### ISSUE THREAD

**Issue by jbelien** [HackYourFutureBelgium/hackyourfuture.be#2]
First things first, congratulations on the new website : it's WAYYY better 🤩

Here are some insights to improve this repository structure:

- [x] Rename `master` branch to `gh-pages` branch (since it's the branch deployed by GitHub Pages)
- [x] Rename `dev` branch in `master` branch (since it's the main branch we have to work on)
- [ ] Clean current `dev` branch:
    - [x] Delete `.cache` folder (+ add to `.gitignore`)
    - [x] Delete `public` folder (useless since the deployed files are in current `master` branch) (+ add to `.gitignore` unless some of the files are needed)
    - [x] Delete `CNAME` file, it's only necessary in the branch deployed by GitHub Pages
    - [ ] Write proper README file (it's still the default Gatsby README file)
- [x] Rename repository (since our main URL is `hackyourfuture.be` it doesn't really make sense to call our repository `HackYourFutureBelgium.github.io`, I would use some as simple as `website`)
- [ ] I see your using GitHub Actions which is awesome ; if I understand correctly, it builds, commits, and pushes to current `master` branch from current `dev`  branch ; unfortunately it failed for the last 3 commits
    - [ ] Fix GitHub Actions workflow
    - [ ] Don't commit anything in current `master` branch (adding the necessary `CNAME` file is of course an exception)
    - [ ] To avoid any commit in current `master` branch, make it protected (see "Branch protection rules" in [settings](https://github.com/HackYourFutureBelgium/HackYourFutureBelgium.github.io/settings/branches))

Those are only suggestions, I just think it will help for better understanding of how it works if anyone else wants to contribute (including myself). Feel free to ask if something isn't clear.

And ... GREAT WORK on the new website 👍

**Comment by colevandersWands** [comment]
Good morning @jbelien, thanks for the issue!  Right now the site (deployment-wise) is in ugly keep-it-working mode so it can be live when we submit the DBSF proposal.  For this quick fix it's in the repsitory called hyfbe.gh.io given how github pages works and that we want the module pages to stay live (ie. hackyourfuture.be/encapsulation)

Michiel will be helping me find a better solution, we'll move the code to a new repository and deploy through Netlify.  At that point I'll document the arrangement in the repo.

And about the branch naming, I wanted to use gh-pages but the username.github.io repositories can only be deployed from master thus the dev branch gymnastics. Just learned this Friday while trying to use the gh-pages branch.  When we move the code back to the /website we'll also switch to better branch naming

**Comment by jbelien** [comment]
- [x] `dev` branch renamed to `main`
- [x] `main` branch deployed on Netlfiy: https://hackyourfuturebe.netlify.app/
- [x] Deleted GitHub Actions that deployed on GitHub Pages
- [x] Delete `master` branch when https://hackyourfuture.be/ is pointing to Netlify
- [x] Delete `HackYourFutureBelgium/website-temp` repository when we are sure everything is working fine
- [x] Create a `develop` branch: every push to `main` branch will be deployed on Netlify ; a `develop` branch allows you to push with deploying it
- [ ] Write proper README file (it was still the default Gatsby README file)
- [x] Keep the libraries up-to-date: I enabled [Dependabot](https://dependabot.com) on the repository ; it will send automatic Pull Request every month with the last version of the libraries

**Comment by jbelien** [comment]
To simplify the deployment (and avoid depending on Netlify), I have setup the deployment here on GitHub Pages using GitHub Actions (see [`deploy.yml`](https://github.com/HackYourFutureBelgium/hackyourfuture.be/blob/main/.github/workflows/deploy.yml))
