### ISSUE TITLE
update Stripe integration

### ISSUE THREAD

**Issue by danielhalasz** [HackYourFutureBelgium/hackyourfuture.be#227]

**Comment by KevinTss** [comment]
@danielhalasz Can you share some instruction here?

1. Does it should stay the same experience?
2. Can you send me the stripe access?

**Comment by danielhalasz** [comment]
LIzhen has registered a new Stripe account, she can give the API details or give access

**Comment by KevinTss** [comment]
Keychanged based on informations received on [this slack thread](https://hackyourfuturebe.slack.com/archives/C044G9B5Z0F/p1669032743955209)
