### ISSUE TITLE
cypress CI currently failing

### ISSUE THREAD

**Issue by lpmi-13** [HackYourFutureBelgium/hackyourfuture.be#24]
it doesn't have the correct config and so is looking at the wrong port (8080 instead of 8000 where gatsby is).

![cypress failure](https://user-images.githubusercontent.com/5070516/95262492-1dfe9300-0824-11eb-9f08-862ca8759b12.png)

**Comment by lpmi-13** [comment]
ah wait...I put the wrong port in the yaml... :facepalm:

**Comment by lpmi-13** [comment]
hmmm...no that doesn't seem to be it...I'll keep investigating

**Comment by jbelien** [comment]
Related to https://github.com/cypress-io/github-action/issues/203 ?

**Comment by jbelien** [comment]
I've disabled the GitHub Action for now.

**Comment by jbelien** [comment]
They fixed the issue.
