### ISSUE TITLE
Add a 'Comment box' in Donation form

### ISSUE THREAD

**Issue by iLienstAr** [HackYourFutureBelgium/hackyourfuture.be#44]
To make the donation form more attractive, we want to add a 'message box' to it.

What do we need:
**Frontend**
- a message box underneath the amount-line in the donation form (both on homepage + support us-page)
- optional: an instruction line where you can choose your own amount, saying 'choose your own donation amount' 

**Backend**
- a way to collect these messages + link them to the donator's mailaddress + name

@jbelien is this clear to you? If not, we can have a quick call.

Deadline would be 1st of December, as the UX Antwerp donation campaign will start.

**Comment by jbelien** [comment]
> @jbelien is this clear to you? If not, we can have a quick call.

Perfectly clear 👌 

> a way to collect these messages + link them to the donator's mailaddress + name

No need for a backend, we should be able to use one of the Stripe description/message field.

**Comment by jbelien** [comment]
@KevinTss Who's managing `https://wt-00b50724a47109acb762597a6836a906-0.sandbox.auth0-extend.com/stripe-payment` ?

Can I have a write access on it ?
Thanks.

**Comment by iLienstAr** [comment]
@jbelien I'm not sure if you're asking permission to our Stripe-account. If that is the case, I can share it with you :)

**Comment by jbelien** [comment]
> @jbelien I'm not sure if you're asking permission to our Stripe-account. If that is the case, I can share it with you :)

I will also need access to the Stripe account (see Slack) but in this case, it's the "backend" used between the website and Stripe.

**Comment by KevinTss** [comment]
@jbelien I don't have any access, I used the code on previous website to make it run. Don't have any details sorry.

And indeed, no backend here, is directly from stripe SDK directly in the client

**Comment by jbelien** [comment]
@MichielLeyman If you have access to the WebTask `https://wt-00b50724a47109acb762597a6836a906-0.sandbox.auth0-extend.com/stripe-payment`, you can delete it. It's not used anymore 🎉
