### ISSUE TITLE
Get bootcamp website offline

### ISSUE THREAD

**Issue by iLienstAr** [HackYourFutureBelgium/hackyourfuture.be#65]
Hey @jbelien and @colevandersWands or @KevinTss :)
Could we get https://bootcamp.hackyourfuture.be/ offline?
It is not up to date at all, so doesn't give a good idea of the current HYF work.
It would be nice if that URL redirects to our homepage (if a redirection is necessary)

**Comment by jbelien** [comment]
I'll take care of it!

**Comment by iLienstAr** [comment]
@jbelien you are a hero and you know!

**Comment by jbelien** [comment]
Sub-domain names `bootcamp.hackyourfuture.be` and `bootcamp.hyf.be` have been deleted.
It may take up to 24 hours to propagate worldwide.

Website is still hosted on Netlify but I don't know who's managing that account ?
@MichielLeyman or @KevinTss  ?

**Comment by jbelien** [comment]
Oops, sorry, I didn't notice you were asking for a redirection to https://hackyourfuture.be/.
I'll take care of it later today.

**Comment by KevinTss** [comment]
Can't help here, never had info about how this domain is handle.

**Comment by jbelien** [comment]
Redirection is now effective. ✔
